---
- name: Converge
  hosts: all
  gather_facts: false

  pre_tasks:
    - name: PRE_TASK | Install python3
      args:
        executable: /bin/sh
      changed_when: false
      ansible.builtin.raw: |
        if command -v apt >/dev/null 2>&1; then
          apt update
          apt -y install python3
        elif command -v dnf >/dev/null 2>&1; then
          dnf makecache
          dnf -y install python3
        elif command -v yum >/dev/null 2>&1; then
          yum makecache
          yum -y install python3
        elif command -v apk >/dev/null 2>&1; then
          apk add --no-cache python3
        fi

  roles:
    - role: xenion1987.ufw
